#服务器端口
server:
  port: 8082
  servlet:
    context-path: /blog
spring:
  # 数据库链接
  datasource:
    url: jdbc:mysql://122.51.201.14:3306/wangxin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: wangxin
    password: wangxin
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      pool-prepared-statements: true
      filters: stat,wall
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    mode: HTML5
    cache: false
  resources:
    static-locations: classpath:/
#  #spring config
#  security:
#    user:
#      name: admin
#      password: admin


#mybatis
mybatis:
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  config-location: classpath:mapper/sqlMapConfig.xml





logging:
  level:
     root: debug
